-- Recipe: Greater Fire Protection Potion corrected drop rate
UPDATE `zp_mangosd`.`creature_loot_template` SET `ChanceOrQuestChance`=2.4 WHERE `item`=13494;

-- LBRS gemstones corrected drop rate
UPDATE `zp_mangosd`.`creature_loot_template` SET `ChanceOrQuestChance`=20 WHERE `item`=12335;
UPDATE `zp_mangosd`.`creature_loot_template` SET `ChanceOrQuestChance`=20 WHERE `item`=12336;
UPDATE `zp_mangosd`.`creature_loot_template` SET `ChanceOrQuestChance`=25 WHERE `item`=12337;

-- Argus Shadow Mage corrected grammar
UPDATE `zp_mangosd`.`creature_ai_texts` SET `content_default`='I\'m tired of this nonsense! Prepare to die!' WHERE  `entry`=-365;

-- Burning Blade Apprentice remove defias quote
DELETE FROM `zp_mangosd`.`creature_ai_scripts` WHERE  `id`=319803;

-- Southshore crier corrected text
UPDATE `zp_scriptdevzerod`.`script_texts` SET `content_default`='Help me! Help! Assassins in the hills! To arms! To arms!' WHERE  `entry`=-1720024;

-- Hunter level 10 quests

REPLACE INTO `zp_mangosd`.`creature_template` (`entry`, `KillCredit1`, `KillCredit2`, `modelid_1`, `modelid_2`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `minhealth`, `maxhealth`, `minmana`, `maxmana`, `armor`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `aggrorangeoverride`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `PetSpellDataId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Civilian`, `RacialLeader`, `RegenHealth`, `equipment_id`, `trainer_id`, `vendor_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES (3601, 0, 0, 1703, 0, 'Dazalar', 'Hunter Trainer', 0, 20, 20, 919, 919, 753, 753, 0, 80, 80, 19, 1.02, 0.95, 0, 0, 24, 31, 0, 13, 1, 2000, 0, 0, 1, 4608, 0, 0, 0, 0, 3, 0, 31.856, 43.802, 100, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 3, 0, 0, 1, 308, 0, 0, 0, 2, 'npc_hunterpetquest');
REPLACE INTO `zp_mangosd`.`creature_template` (`entry`, `KillCredit1`, `KillCredit2`, `modelid_1`, `modelid_2`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `minhealth`, `maxhealth`, `minmana`, `maxmana`, `armor`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `aggrorangeoverride`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `PetSpellDataId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Civilian`, `RacialLeader`, `RegenHealth`, `equipment_id`, `trainer_id`, `vendor_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES (3171, 0, 0, 3744, 0, 'Thotar', 'Hunter Trainer', 4017, 16, 16, 695, 695, 596, 596, 20, 29, 29, 19, 1.1, 0.95, 0, 0, 17, 23, 0, 9, 1, 2000, 2035, 0, 1, 4608, 0, 0, 0, 0, 3, 0, 26.048, 35.816, 100, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'EventAI', 0, 3, 0, 0, 1, 920, 0, 0, 0, 2, 'npc_hunterpetquest');
REPLACE INTO `zp_mangosd`.`creature_template` (`entry`, `KillCredit1`, `KillCredit2`, `modelid_1`, `modelid_2`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `minhealth`, `maxhealth`, `minmana`, `maxmana`, `armor`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `aggrorangeoverride`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `PetSpellDataId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Civilian`, `RacialLeader`, `RegenHealth`, `equipment_id`, `trainer_id`, `vendor_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES (1231, 0, 0, 3558, 0, 'Grif Wildheart', 'Hunter Trainer', 0, 12, 12, 500, 500, 444, 444, 20, 55, 55, 19, 0.97, 0.95, 0, 0, 12, 14, 0, 6, 1, 1500, 0, 0, 1, 4608, 0, 0, 0, 0, 3, 0, 19.9584, 27.4428, 100, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 3, 0, 0, 1, 10, 0, 0, 0, 2, 'npc_hunterpetquest');
REPLACE INTO `zp_mangosd`.`creature_template` (`entry`, `KillCredit1`, `KillCredit2`, `modelid_1`, `modelid_2`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `minhealth`, `maxhealth`, `minmana`, `maxmana`, `armor`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `aggrorangeoverride`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `PetSpellDataId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Civilian`, `RacialLeader`, `RegenHealth`, `equipment_id`, `trainer_id`, `vendor_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES (3065, 0, 0, 3811, 0, 'Yaw Sharpmane', 'Hunter Trainer', 4012, 11, 11, 456, 456, 406, 406, 20, 104, 104, 19, 0.97, 0.95, 1.35, 0, 12, 14, 0, 6, 1, 2000, 0, 0, 1, 4608, 0, 0, 0, 0, 3, 0, 18.392, 25.289, 100, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 1, 0, 0, 1, 127, 0, 0, 0, 2, 'npc_hunterpetquest');
