-- Recipe: Greater Fire Protection Potion corrected drop rate
UPDATE `zp_mangosd`.`creature_loot_template` SET `ChanceOrQuestChance`=2.4 WHERE `item`=13494;

-- LBRS gemstones corrected drop rate
UPDATE `zp_mangosd`.`creature_loot_template` SET `ChanceOrQuestChance`=20 WHERE `item`=12335;
UPDATE `zp_mangosd`.`creature_loot_template` SET `ChanceOrQuestChance`=20 WHERE `item`=12336;
UPDATE `zp_mangosd`.`creature_loot_template` SET `ChanceOrQuestChance`=25 WHERE `item`=12337;

-- Argus Shadow Mage corrected grammar
UPDATE `zp_mangosd`.`creature_ai_texts` SET `content_default`='I\'m tired of this nonsense! Prepare to die!' WHERE  `entry`=-365;

-- Burning Blade Apprentice remove defias quote
DELETE FROM `zp_mangosd`.`creature_ai_scripts` WHERE  `id`=319803;

-- Southshore crier corrected text
UPDATE `zp_scriptdevzerod`.`script_texts` SET `content_default`='Help me! Help! Assassins in the hills! To arms! To arms!' WHERE  `entry`=-1720024;

-- Hunter level 10 quests

REPLACE INTO `zp_mangosd`.`creature_template` (`entry`, `KillCredit1`, `KillCredit2`, `modelid_1`, `modelid_2`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `minhealth`, `maxhealth`, `minmana`, `maxmana`, `armor`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `aggrorangeoverride`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `PetSpellDataId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Civilian`, `RacialLeader`, `RegenHealth`, `equipment_id`, `trainer_id`, `vendor_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES (3601, 0, 0, 1703, 0, 'Dazalar', 'Hunter Trainer', 0, 20, 20, 919, 919, 753, 753, 0, 80, 80, 19, 1.02, 0.95, 0, 0, 24, 31, 0, 13, 1, 2000, 0, 0, 1, 4608, 0, 0, 0, 0, 3, 0, 31.856, 43.802, 100, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 3, 0, 0, 1, 308, 0, 0, 0, 2, 'npc_hunterpetquest');
REPLACE INTO `zp_mangosd`.`creature_template` (`entry`, `KillCredit1`, `KillCredit2`, `modelid_1`, `modelid_2`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `minhealth`, `maxhealth`, `minmana`, `maxmana`, `armor`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `aggrorangeoverride`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `PetSpellDataId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Civilian`, `RacialLeader`, `RegenHealth`, `equipment_id`, `trainer_id`, `vendor_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES (3171, 0, 0, 3744, 0, 'Thotar', 'Hunter Trainer', 4017, 16, 16, 695, 695, 596, 596, 20, 29, 29, 19, 1.1, 0.95, 0, 0, 17, 23, 0, 9, 1, 2000, 2035, 0, 1, 4608, 0, 0, 0, 0, 3, 0, 26.048, 35.816, 100, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'EventAI', 0, 3, 0, 0, 1, 920, 0, 0, 0, 2, 'npc_hunterpetquest');
REPLACE INTO `zp_mangosd`.`creature_template` (`entry`, `KillCredit1`, `KillCredit2`, `modelid_1`, `modelid_2`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `minhealth`, `maxhealth`, `minmana`, `maxmana`, `armor`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `aggrorangeoverride`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `PetSpellDataId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Civilian`, `RacialLeader`, `RegenHealth`, `equipment_id`, `trainer_id`, `vendor_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES (1231, 0, 0, 3558, 0, 'Grif Wildheart', 'Hunter Trainer', 0, 12, 12, 500, 500, 444, 444, 20, 55, 55, 19, 0.97, 0.95, 0, 0, 12, 14, 0, 6, 1, 1500, 0, 0, 1, 4608, 0, 0, 0, 0, 3, 0, 19.9584, 27.4428, 100, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 3, 0, 0, 1, 10, 0, 0, 0, 2, 'npc_hunterpetquest');
REPLACE INTO `zp_mangosd`.`creature_template` (`entry`, `KillCredit1`, `KillCredit2`, `modelid_1`, `modelid_2`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `minhealth`, `maxhealth`, `minmana`, `maxmana`, `armor`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `aggrorangeoverride`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `PetSpellDataId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Civilian`, `RacialLeader`, `RegenHealth`, `equipment_id`, `trainer_id`, `vendor_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES (3065, 0, 0, 3811, 0, 'Yaw Sharpmane', 'Hunter Trainer', 4012, 11, 11, 456, 456, 406, 406, 20, 104, 104, 19, 0.97, 0.95, 1.35, 0, 12, 14, 0, 6, 1, 2000, 0, 0, 1, 4608, 0, 0, 0, 0, 3, 0, 18.392, 25.289, 100, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 1, 0, 0, 1, 127, 0, 0, 0, 2, 'npc_hunterpetquest');

-- Remove Empty Tainted Ooze Jar from loot tables of a lockbox and mobs
DELETE FROM `zp_mangosd`.`item_loot_template` WHERE (`entry`='5758') AND (`item`='11948');
DELETE FROM `zp_mangosd`.`creature_loot_template` WHERE (`item`='11948');
-- Remove Empty Cursed Ooze Jar from loot tables of a lockbox and mobs
DELETE FROM `zp_mangosd`.`item_loot_template` WHERE (`entry`='5758') AND (`item`='11914');
DELETE FROM `zp_mangosd`.`creature_loot_template` WHERE (`item`='11914');

-- Adjusted loot tables for Zum'rah (grey/green loot added)
REPLACE INTO `zp_mangosd`.`creature_loot_template` VALUES ('7271', '24043', '30', '0', '-24043', '1', '0', '0', '0');
REPLACE INTO `zp_mangosd`.`creature_loot_template` VALUES ('7271', '24036', '15', '0', '-24036', '1', '0', '0', '0');

-- Fix typos in the quest "Tainted Memorandum"
REPLACE INTO `zp_mangosd`.`quest_template` VALUES ('3115', '2', '-61', '1', '1', '0', '256', '64', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '179', '0', '0', '0', '9577', '1', '0', 'Tainted Memorandum', 'While you were helping me out, this memorandum was given to me to pass on to you. Take some time to read it when you have a chance. I\'m thinkin\' it came from the warlock trainer Alamar. Take a gander at it and go find him inside Anvilmar when you\'ve a chance.$B$BAnd watch yerself, $N, your kind ain\'t too trusted \'round these parts.', 'Read the Tainted Memorandum and speak to Alamar Grimm inside Anvilmar above Coldridge Valley.', 'But none of that matters. What matters is that you\'ve seen your own Holy Light! You know where power truly comes from. You realize that having our own allies is much more... prudent. Special allies. Allies that, no matter the task, will obey till their last breath.$b$bAnd that\'s where I come in, $N. I can train you in the beginnings of those special powers. Seek me out often and I will do what I can to teach you more spells.', 'Wonderful! You got my memorandum obviously.$b$bIgnore the fools around you, $N. The Holy Light?! The sword and shield?! These aren\'t paths for ones as open minded as us. Look at what \"normal\" magic did to our home. Coupled with those damned tinkerers, our race almost became extinct. And now we have to rely on the dwarves-- they\'d rather spend time allying with humans than help us rebuild our own home. We\'re like second-class citizens. Have you seen the way they look at us?', '', '', '', '', '', '9577', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '54', '0', '0', '0', '0', '50', '0', '0', '0', '0', '0', '30', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');

